Feat/delete skill
MLH-Fellowship/orientation-project-python-23.SUM.A pull request #28
Opened 2023-06-02 17:51 UTC by Raajheer1

Issue #3 
Added a DELETE route which deletes the skill by index, also added test case in test_pytest.py

2023-06-02 21:43 UTC, wrussell1999 commented
Hey @Raajheer1, in future make sure to comment on the issue that you’re contributing to it to prevent others creating duplicate code

2023-06-02 23:02 UTC, wrussell1999 commented
@Raajheer1, to get it merged, make this change and we’re good to go!

2023-06-06 19:42 UTC, Henoven commented
Hey @wrussell1999, 
Could you please review it again? @Raajheer1 told me he is done with the changes.
I can help you review this Tomorrow morning, let me know if I can help you : )

2023-06-07 08:26 UTC, wrussell1999 requested changes

2023-06-07 14:56 UTC, Raajheer1 commented on test_pytest.py
> +    correct_response = {"Success": "Skill deleted"}
Hey @wrussell1999 I fixed this by changing the assertion using the same syntax as the other tests.

2026-07-25 17:27 UTC, closed without merging