Feat/spell check on content
MLH-Fellowship/orientation-project-python-23.SUM.A pull request #32
Opened 2023-06-03 14:01 UTC by galadd

2023-06-03 17:54 UTC, galadd commented
#11

2023-06-06 19:22 UTC, Henoven requested changes
It seems your solution should work and solve #11 However, I see that there are some things that you should address first, before approving this PR.

2023-06-07 07:50 UTC, galadd commented on test_pytest.py
> +# from models import Experience
When I initially cloned the repo, and ran the test, it failed. So I commented it all out and focused only on the test for the function I'll be writing

2023-06-07 07:58 UTC, galadd commented on utils.py
> +    for attr in data:
> @galadd What is `attr` standing for?

attr represents the whole field for Experience, Education or Skill

2023-06-08 10:01 UTC, closed without merging